// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: video.proto

package ent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BiliBiliVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title    string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	PostAt   int64    `protobuf:"varint,3,opt,name=PostAt,proto3" json:"PostAt,omitempty"`
	Author   string   `protobuf:"bytes,4,opt,name=Author,proto3" json:"Author,omitempty"`
	View     uint32   `protobuf:"varint,5,opt,name=View,proto3" json:"View,omitempty"`
	Like     uint32   `protobuf:"varint,6,opt,name=Like,proto3" json:"Like,omitempty"`
	Coin     uint32   `protobuf:"varint,7,opt,name=Coin,proto3" json:"Coin,omitempty"`
	Favorite uint32   `protobuf:"varint,8,opt,name=Favorite,proto3" json:"Favorite,omitempty"`
	Share    uint32   `protobuf:"varint,9,opt,name=Share,proto3" json:"Share,omitempty"`
	Keywords []string `protobuf:"bytes,10,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
}

func (x *BiliBiliVideo) Reset() {
	*x = BiliBiliVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiliBiliVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiliBiliVideo) ProtoMessage() {}

func (x *BiliBiliVideo) ProtoReflect() protoreflect.Message {
	mi := &file_video_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiliBiliVideo.ProtoReflect.Descriptor instead.
func (*BiliBiliVideo) Descriptor() ([]byte, []int) {
	return file_video_proto_rawDescGZIP(), []int{0}
}

func (x *BiliBiliVideo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BiliBiliVideo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BiliBiliVideo) GetPostAt() int64 {
	if x != nil {
		return x.PostAt
	}
	return 0
}

func (x *BiliBiliVideo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BiliBiliVideo) GetView() uint32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *BiliBiliVideo) GetLike() uint32 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *BiliBiliVideo) GetCoin() uint32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *BiliBiliVideo) GetFavorite() uint32 {
	if x != nil {
		return x.Favorite
	}
	return 0
}

func (x *BiliBiliVideo) GetShare() uint32 {
	if x != nil {
		return x.Share
	}
	return 0
}

func (x *BiliBiliVideo) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_video_proto protoreflect.FileDescriptor

var file_video_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x65,
	0x6e, 0x74, 0x22, 0xef, 0x01, 0x0a, 0x0d, 0x42, 0x69, 0x6c, 0x69, 0x42, 0x69, 0x6c, 0x69, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74,
	0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x56, 0x69,
	0x65, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12,
	0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x4c, 0x69,
	0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4b, 0x65, 0x79, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x61, 0x70, 0x70, 0x2f, 0x65, 0x6e, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_video_proto_rawDescOnce sync.Once
	file_video_proto_rawDescData = file_video_proto_rawDesc
)

func file_video_proto_rawDescGZIP() []byte {
	file_video_proto_rawDescOnce.Do(func() {
		file_video_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_proto_rawDescData)
	})
	return file_video_proto_rawDescData
}

var file_video_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_video_proto_goTypes = []interface{}{
	(*BiliBiliVideo)(nil), // 0: ent.BiliBiliVideo
}
var file_video_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_proto_init() }
func file_video_proto_init() {
	if File_video_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_video_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiliBiliVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_proto_goTypes,
		DependencyIndexes: file_video_proto_depIdxs,
		MessageInfos:      file_video_proto_msgTypes,
	}.Build()
	File_video_proto = out.File
	file_video_proto_rawDesc = nil
	file_video_proto_goTypes = nil
	file_video_proto_depIdxs = nil
}
